"""
reporter.py — build markdown report + CSV output files, upload to S3.

Consumes output from signal_quality, regime_analysis, score_analysis, attribution,
and (when available) vectorbt portfolio stats. Writes:
    - results/{date}/report.md
    - results/{date}/signal_quality.csv
    - results/{date}/metrics.json
    - s3://alpha-engine-research/backtest/{date}/report.md  (if upload=True)
"""

import json
import logging
import os
from datetime import date
from pathlib import Path

import boto3
import pandas as pd
from botocore.exceptions import ClientError

logger = logging.getLogger(__name__)


def build_report(
    run_date: str,
    signal_quality: dict,
    regime_analysis: list[dict],
    score_analysis: list[dict],
    attribution: dict,
    portfolio_stats: dict | None = None,
    sweep_df=None,
    weight_result: dict | None = None,
    config: dict | None = None,
    predictor_stats: dict | None = None,
    predictor_sweep_df=None,
    veto_result: dict | None = None,
    executor_rec: dict | None = None,
) -> str:
    """
    Build a markdown report string from analysis results.

    Returns the markdown string (also written to disk by save()).
    """
    lines = [
        f"# Alpha Engine Backtest Report",
        f"_Run date: {run_date}_",
        "",
        "---",
        "",
    ]

    # Signal quality summary
    lines += _section_signal_quality(signal_quality)
    lines += [""]

    # Score threshold analysis
    lines += _section_score_analysis(score_analysis)
    lines += [""]

    # Regime breakdown
    lines += _section_regime(regime_analysis)
    lines += [""]

    # Attribution
    lines += _section_attribution(attribution)
    lines += [""]

    # Portfolio simulation (Mode 2)
    if portfolio_stats:
        lines += _section_portfolio(portfolio_stats)
        lines += [""]

    # Param sweep
    if sweep_df is not None and not sweep_df.empty:
        lines += _section_param_sweep(sweep_df)
        lines += [""]

    # Weight recommendation
    if weight_result:
        lines += _section_weight_recommendation(weight_result)
        lines += [""]

    # Veto threshold analysis
    if veto_result:
        lines += _section_veto_analysis(veto_result)
        lines += [""]

    # Executor parameter recommendations
    if executor_rec:
        lines += _section_executor_recommendations(executor_rec)
        lines += [""]

    # Predictor-only backtest (2y historical)
    if predictor_stats:
        lines += _section_predictor_backtest(predictor_stats)
        lines += [""]

    # Predictor param sweep
    if predictor_sweep_df is not None and not predictor_sweep_df.empty:
        lines += _section_param_sweep_predictor(predictor_sweep_df)
        lines += [""]

    lines += [
        "---",
        f"_Generated by alpha-engine-backtester — {run_date}_",
    ]

    return "\n".join(lines)


def save(
    report_md: str,
    signal_quality: dict,
    score_analysis: list[dict],
    sweep_df=None,
    attribution: dict | None = None,
    run_date: str | None = None,
    results_dir: str = "results",
) -> Path:
    """
    Write report.md, signal_quality.csv, and metrics.json to results/{date}/.

    Returns the output directory path.
    """
    if run_date is None:
        run_date = date.today().isoformat()

    out_dir = Path(results_dir) / run_date
    out_dir.mkdir(parents=True, exist_ok=True)

    # Markdown report
    (out_dir / "report.md").write_text(report_md)
    logger.info("Wrote %s", out_dir / "report.md")

    # Signal quality CSV
    if score_analysis:
        df = pd.DataFrame(score_analysis)
        df.to_csv(out_dir / "signal_quality.csv", index=False)
        logger.info("Wrote %s", out_dir / "signal_quality.csv")

    # Metrics JSON (overall summary)
    overall = signal_quality.get("overall", {})
    metrics = {
        "run_date": run_date,
        "status": signal_quality.get("status"),
        **overall,
    }
    (out_dir / "metrics.json").write_text(json.dumps(metrics, indent=2, default=str))
    logger.info("Wrote %s", out_dir / "metrics.json")

    # Param sweep CSV
    if sweep_df is not None and not sweep_df.empty:
        sweep_df.to_csv(out_dir / "param_sweep.csv", index=False)
        logger.info("Wrote %s", out_dir / "param_sweep.csv")

    # Attribution JSON
    if attribution and attribution.get("status") == "ok":
        (out_dir / "attribution.json").write_text(json.dumps(attribution, indent=2, default=str))
        logger.info("Wrote %s", out_dir / "attribution.json")

    return out_dir


def upload_to_s3(
    local_dir: Path,
    bucket: str,
    prefix: str = "backtest",
    run_date: str | None = None,
) -> None:
    """
    Upload all files in local_dir to s3://{bucket}/{prefix}/{run_date}/.
    """
    if run_date is None:
        run_date = date.today().isoformat()

    s3 = boto3.client("s3")
    for file_path in local_dir.iterdir():
        key = f"{prefix}/{run_date}/{file_path.name}"
        try:
            s3.upload_file(str(file_path), bucket, key)
            logger.info("Uploaded s3://%s/%s", bucket, key)
        except ClientError as e:
            logger.error("Failed to upload %s: %s", file_path, e)
            raise


# --- Section builders ---

def _section_signal_quality(sq: dict) -> list[str]:
    lines = ["## Mode 1 — Signal Quality"]
    status = sq.get("status", "unknown")

    if status == "insufficient_data":
        lines += [
            "",
            f"> **Insufficient data.** "
            f"{sq.get('rows_10d_populated', 0)} rows with 10d returns populated "
            f"(need {sq.get('rows_needed', 10)}). "
            "Results will be available after Week 4 (~200 populated rows).",
        ]
        return lines

    overall = sq.get("overall", {})
    acc_10d = overall.get("accuracy_10d")
    acc_30d = overall.get("accuracy_30d")
    n_10d = overall.get("n_10d", 0)
    n_30d = overall.get("n_30d", 0)

    lines += [
        "",
        f"| Metric | 10d | 30d |",
        f"|--------|-----|-----|",
        f"| Accuracy vs SPY | {_pct(acc_10d)} (n={n_10d}) | {_pct(acc_30d)} (n={n_30d}) |",
        f"| Avg alpha | {_pct(overall.get('avg_alpha_10d'))} | {_pct(overall.get('avg_alpha_30d'))} |",
        "",
        "> 50% = coin flip. 55%+ over 30+ signals suggests real alpha.",
    ]

    buckets = sq.get("by_score_bucket", [])
    if buckets:
        lines += ["", "### By score bucket", ""]
        lines += ["| Bucket | Acc 10d | Acc 30d | Avg α 10d | n | FDR |"]
        lines += ["|--------|---------|---------|-----------|---|-----|"]
        has_exploratory = False
        has_fdr_exploratory = False
        for b in buckets:
            star = ""
            if b.get("exploratory"):
                star = "*"
                has_exploratory = True
            fdr_tag = ""
            if b.get("fdr_exploratory"):
                fdr_tag = "†"
                has_fdr_exploratory = True
            lines.append(
                f"| {b.get('bucket')} | {_pct(b.get('accuracy_10d'))}{star} | "
                f"{_pct(b.get('accuracy_30d'))}{star} | {_pct(b.get('avg_alpha_10d'))}{star} | "
                f"{b.get('n_10d', 0)} | {fdr_tag} |"
            )
        if has_exploratory:
            lines += ["", "\\* exploratory — fewer than 20 samples, treat with caution"]
        if has_fdr_exploratory:
            lines += ["", "† not FDR-significant (Benjamini-Hochberg, α=0.05) — accuracy may not differ from coin flip"]

    return lines


def _section_score_analysis(rows: list[dict]) -> list[str]:
    lines = ["## Score threshold analysis"]
    if not rows:
        lines += ["", "> Deferred until Week 4+ (insufficient data)."]
        return lines

    lines += ["", "| Min score | Acc 10d | Acc 30d | n |"]
    lines += ["|-----------|---------|---------|---|"]
    for r in rows:
        lines.append(
            f"| {r.get('threshold')} | {_pct(r.get('accuracy_10d'))} | "
            f"{_pct(r.get('accuracy_30d'))} | {r.get('n_10d', 0)} |"
        )
    return lines


def _section_regime(rows: list[dict]) -> list[str]:
    lines = ["## Regime analysis"]
    if not rows:
        lines += ["", "> Deferred until Week 4+ (insufficient data)."]
        return lines

    lines += ["", "| Regime | Acc 10d | Acc 30d | n |"]
    lines += ["|--------|---------|---------|---|"]
    for r in rows:
        lines.append(
            f"| {r.get('market_regime')} | {_pct(r.get('accuracy_10d'))} | "
            f"{_pct(r.get('accuracy_30d'))} | {r.get('n_10d', 0)} |"
        )
    return lines


def _section_attribution(attr: dict) -> list[str]:
    lines = ["## Sub-score attribution"]
    status = attr.get("status", "unknown")

    if status != "ok":
        lines += [
            "",
            f"> **Deferred.** {attr.get('note', 'Insufficient data.')}",
        ]
        return lines

    lines += [
        "",
        f"Analyzed {attr.get('rows_analyzed', 0)} signals.",
        "",
        "### Correlation with beat_spy_10d",
        "",
        "| Sub-score | Corr (10d) | Corr (30d) | FDR sig (10d) | FDR sig (30d) |",
        "|-----------|------------|------------|---------------|---------------|",
    ]
    for label, corrs in attr.get("correlations", {}).items():
        c10 = corrs.get("beat_spy_10d")
        c30 = corrs.get("beat_spy_30d")
        fdr_10 = "Yes" if corrs.get("beat_spy_10d_fdr_significant") else "No"
        fdr_30 = "Yes" if corrs.get("beat_spy_30d_fdr_significant") else "No"
        lines.append(f"| {label} | {_fmt(c10)} | {_fmt(c30)} | {fdr_10} | {fdr_30} |")

    ranking_10d = attr.get("ranking_10d", [])
    if ranking_10d:
        lines += ["", f"**Strongest predictor (10d):** {ranking_10d[0]}"]

    fdr_ns = attr.get("fdr_non_significant")
    if fdr_ns:
        lines += ["", f"> FDR non-significant: {', '.join(fdr_ns)}"]

    lines += ["", f"> {attr.get('note', '')}"]
    return lines


def _section_portfolio(stats: dict) -> list[str]:
    status = stats.get("status")
    if status and status != "ok":
        note = stats.get("note", stats.get("error", "No details available."))
        return [
            "## Mode 2 — Portfolio simulation",
            "",
            f"> **Skipped.** {note}",
        ]
    lines = [
        "## Mode 2 — Portfolio simulation",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Total return | {_pct(stats.get('total_return'))} |",
        f"| Sharpe ratio | {_fmt(stats.get('sharpe_ratio'))} |",
        f"| Max drawdown | {_pct(stats.get('max_drawdown'))} |",
        f"| Calmar ratio | {_fmt(stats.get('calmar_ratio'))} |",
        f"| Total trades | {stats.get('total_trades', 'N/A')} |",
        f"| Win rate | {_pct(stats.get('win_rate'))} |",
    ]
    sim_assumptions = stats.get("simulation_assumptions")
    if sim_assumptions:
        lines.append(f"| Simulation | {sim_assumptions} |")
    price_gaps = stats.get("price_gap_warnings")
    if price_gaps:
        lines += ["", f"> **Price gap warnings:** {price_gaps}"]
    staleness = stats.get("staleness_warning")
    if staleness:
        lines += [f"> **{staleness}**"]
    return lines


def _section_weight_recommendation(result: dict) -> list[str]:
    lines = ["## Scoring weight recommendation"]
    status = result.get("status")

    if status in ("insufficient_data", "no_subscores", "error"):
        lines += ["", f"> **Deferred.** {result.get('note', result.get('error', 'Unavailable.'))}"]
        return lines

    n = result.get("n_samples", 0)
    confidence = result.get("confidence", "unknown")
    current = result.get("current_weights", {})
    suggested = result.get("suggested_weights", {})
    changes = result.get("changes", {})
    correlations = result.get("correlations", {})

    blend_factor = result.get("blend_factor")
    blend_str = f" · blend: {blend_factor:.2f}" if blend_factor is not None else ""
    lines += [
        "",
        f"_n={n} signals · confidence: {confidence}{blend_str}_",
        "",
        "| Sub-score | Current | Corr (10d) | Corr (30d) | Suggested | Change |",
        "|-----------|---------|------------|------------|-----------|--------|",
    ]
    for k in ("news", "research"):
        corr = correlations.get(k, {})
        c10 = corr.get("beat_spy_10d")
        c30 = corr.get("beat_spy_30d")
        chg = changes.get(k, 0)
        chg_str = f"+{chg:.1%}" if chg > 0 else f"{chg:.1%}"
        lines.append(
            f"| {k} | {_pct(current.get(k))} | {_fmt(c10)} | {_fmt(c30)} "
            f"| {_pct(suggested.get(k))} | {chg_str} |"
        )

    apply = result.get("apply_result", {})
    if apply.get("applied"):
        lines += [
            "",
            f"> ✅ **Weights updated automatically** in S3 (`config/scoring_weights.json`). "
            f"Research Lambda will use new weights on next cold-start. "
            f"n={apply.get('n_samples')}, confidence={apply.get('confidence')}.",
        ]
    else:
        reason = apply.get("reason", "guardrails not met")
        lines += [
            "",
            f"> ⏸ **Not applied** — {reason}.",
        ]

    # Recommendation stability (Gap #4)
    stability = result.get("stability", {})
    if stability.get("weeks_loaded", 0) > 0:
        if stability.get("stable"):
            lines += [f"> Recommendation stability: {stability['weeks_loaded'] + 1}/{stability['weeks_loaded'] + 1} weeks consistent"]
        else:
            reversals = stability.get("reversals", [])
            for rev in reversals:
                lines += [f"> WARNING: {rev}"]

    lines += [f"> {result.get('note', '')}"]
    return lines


def _section_predictor_backtest(stats: dict) -> list[str]:
    """Build report section for predictor-only backtest results."""
    lines = ["## Predictor-Only Backtest (2y historical)"]
    status = stats.get("status", "unknown")

    if status in ("insufficient_data", "error"):
        note = stats.get("note", stats.get("error", "Unavailable."))
        lines += ["", f"> **Deferred.** {note}"]
        return lines

    if status == "no_orders":
        lines += [
            "",
            "> No ENTER signals passed risk rules during the simulation period.",
            f"> Dates simulated: {stats.get('dates_simulated', 'N/A')}",
        ]
        return lines

    meta = stats.get("predictor_metadata", {})
    lines += [
        "",
        f"_GBM-only signals (no LLM research component). "
        f"{meta.get('n_tickers', 'N/A')} tickers, "
        f"{meta.get('n_dates', 'N/A')} trading days "
        f"({meta.get('date_range_start', '?')} → {meta.get('date_range_end', '?')}). "
        f"Top {meta.get('top_n_per_day', 'N/A')} ENTER signals/day, "
        f"min score {meta.get('min_score', 'N/A')}._",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| **Total alpha** | **{_pct(stats.get('total_alpha'))}** |",
        f"| Total return | {_pct(stats.get('total_return'))} |",
        f"| SPY return | {_pct(stats.get('spy_return'))} |",
        f"| Sharpe ratio | {_fmt(stats.get('sharpe_ratio'))} |",
        f"| Max drawdown | {_pct(stats.get('max_drawdown'))} |",
        f"| Calmar ratio | {_fmt(stats.get('calmar_ratio'))} |",
        f"| Total trades | {stats.get('total_trades', 'N/A')} |",
        f"| Win rate | {_pct(stats.get('win_rate'))} |",
        f"| Dates simulated | {stats.get('dates_simulated', 'N/A')} |",
        f"| Total orders | {stats.get('total_orders', 'N/A')} |",
        "",
        "> This tests the full executor pipeline (risk guard, position sizing, ATR stops, "
        "time decay, graduated drawdown) using GBM predictions on historical price data. "
        "Macro context is neutral; sector ratings are market-weight.",
    ]
    return lines


def _section_param_sweep_predictor(df) -> list[str]:
    """Build report section for predictor-only param sweep results."""
    lines = ["## Predictor param sweep — top combinations by total alpha", ""]
    param_cols = [c for c in df.columns if c not in [
        "total_return", "total_alpha", "spy_return", "sharpe_ratio", "max_drawdown",
        "calmar_ratio", "total_trades", "win_rate", "status", "dates_simulated",
        "total_orders", "note", "error",
    ]]
    stat_cols = [c for c in ["total_alpha", "sharpe_ratio", "total_return", "spy_return", "max_drawdown", "win_rate"] if c in df.columns]
    show_cols = param_cols + stat_cols
    header = "| " + " | ".join(show_cols) + " |"
    sep    = "| " + " | ".join("---" for _ in show_cols) + " |"
    lines += [header, sep]
    for _, row in df.head(10).iterrows():
        cells = []
        for c in show_cols:
            v = row.get(c)
            if c in ("total_return", "total_alpha", "spy_return", "max_drawdown", "win_rate"):
                cells.append(_pct(v))
            elif c in ("sharpe_ratio",):
                cells.append(_fmt(v))
            else:
                cells.append(str(v) if v is not None else "—")
        lines.append("| " + " | ".join(cells) + " |")
    lines += ["", f"_Full results in param_sweep.csv (predictor-only)_"]
    return lines


def _section_param_sweep(df) -> list[str]:
    # Sweep metadata from DataFrame attrs
    sweep_mode = df.attrs.get("sweep_mode", "grid")
    sweep_trials = df.attrs.get("sweep_trials", len(df))
    sweep_total = df.attrs.get("sweep_total_grid", len(df))
    sweep_coverage = df.attrs.get("sweep_coverage", 1.0)

    title = "## Param sweep — top combinations by Sharpe ratio"
    if sweep_mode != "grid":
        title += f" ({sweep_mode}: {sweep_trials}/{sweep_total} combos, {sweep_coverage:.0%} coverage)"

    lines = [title, ""]
    param_cols = [c for c in df.columns if c not in [
        "total_return", "total_alpha", "spy_return", "sharpe_ratio",
        "max_drawdown", "calmar_ratio", "total_trades", "win_rate",
        "status", "dates_simulated", "total_orders", "note", "error",
    ]]
    stat_cols = [c for c in ["total_alpha", "sharpe_ratio", "total_return", "spy_return", "max_drawdown", "win_rate"] if c in df.columns]
    show_cols = param_cols + stat_cols
    header = "| " + " | ".join(show_cols) + " |"
    sep    = "| " + " | ".join("---" for _ in show_cols) + " |"
    lines += [header, sep]
    for _, row in df.head(10).iterrows():
        cells = []
        for c in show_cols:
            v = row.get(c)
            if c in ("total_return", "total_alpha", "spy_return", "max_drawdown", "win_rate"):
                cells.append(_pct(v))
            elif c in ("sharpe_ratio",):
                cells.append(_fmt(v))
            else:
                cells.append(str(v) if v is not None else "—")
        lines.append("| " + " | ".join(cells) + " |")
    lines += ["", f"_Full results in param_sweep.csv_"]
    return lines


def _section_veto_analysis(result: dict) -> list[str]:
    lines = ["## Predictor veto threshold analysis"]
    status = result.get("status", "unknown")

    if status not in ("ok", "insufficient_lift"):
        note = result.get("note", result.get("error", "Unavailable."))
        lines += ["", f"> **Deferred.** {note}"]
        return lines

    current = result.get("current_threshold", 0.65)
    recommended = result.get("recommended_threshold")
    n_down = result.get("n_down_predictions", 0)
    base_rate = result.get("base_rate")

    base_rate_str = f" Base rate (BUY signals beating SPY): {_pct(base_rate)}." if base_rate is not None else ""
    lines += [
        "",
        f"_Analyzed {n_down} DOWN predictions with resolved outcomes.{base_rate_str}_",
        "",
        "| Confidence | Vetoes | True neg | False neg | Precision | CI 95% | Lift | Missed α (total) | Missed α/winner |",
        "|------------|--------|----------|-----------|-----------|--------|------|------------------|-----------------|",
    ]
    for t in result.get("thresholds", []):
        conf = t["confidence"]
        marker = ""
        if conf == current:
            marker = " (current)"
        if conf == recommended:
            marker = " **→**"
        prec = _pct(t["precision"]) if t["precision"] is not None else "—"
        ci = t.get("precision_ci_95")
        ci_str = f"[{ci[0]:.0%}–{ci[1]:.0%}]" if ci else "—"
        if t.get("low_confidence"):
            ci_str += "†"
        lift = t.get("lift")
        lift_str = f"{lift:+.1%}" if lift is not None else "—"
        missed_pw = t.get("missed_alpha_per_winner", 0)
        lines.append(
            f"| {conf:.2f}{marker} | {t['n_vetoes']} | {t['true_negatives']} "
            f"| {t['false_negatives']} | {prec} | {ci_str} | {lift_str} "
            f"| {t['missed_alpha']:.4f} | {missed_pw:.4f} |"
        )

    lines += ["", "† Low confidence — fewer than 30 veto decisions"]

    if recommended is not None:
        lines += ["", f"> **Recommended:** {recommended:.2f} — {result.get('recommendation_reason', '')}"]
    else:
        lines += ["", f"> {result.get('recommendation_reason', 'No recommendation.')}"]

    # Cost sensitivity (Gap #10)
    cost_sens = result.get("cost_sensitivity")
    if cost_sens:
        details = result.get("cost_sensitivity_details", {})
        lines += [f"> Cost sensitivity: **{cost_sens}** — thresholds by cost_weight: {details}"]

    apply = result.get("apply_result", {})
    if apply.get("applied"):
        lines += [
            f"> ✅ **Veto threshold updated** in S3 (`config/predictor_params.json`). "
            f"Predictor Lambda will use {apply.get('veto_confidence'):.2f} on next cold-start.",
        ]
    else:
        reason = apply.get("reason", "guardrails not met")
        lines += [f"> ⏸ **Not applied** — {reason}."]

    return lines


def _section_executor_recommendations(result: dict) -> list[str]:
    lines = ["## Executor parameter recommendations"]
    status = result.get("status", "unknown")

    if status != "ok":
        note = result.get("note", result.get("error", "Unavailable."))
        lines += ["", f"> **Deferred.** {note}"]
        return lines

    baseline = result.get("baseline_params", {})
    recommended = result.get("recommended_params", {})
    factory = result.get("factory_defaults", {})
    improvement = result.get("improvement_pct", 0)

    best_alpha = result.get("best_alpha")
    alpha_str = f" | Best alpha: {best_alpha:.1%}" if best_alpha is not None else ""

    baseline_rank = result.get("baseline_combo_rank")
    n_combos = result.get("n_combos_tested", "?")
    baseline_note = ""
    if baseline_rank is not None:
        baseline_note = f" Baseline: combo #{baseline_rank} of {n_combos} (closest to current S3 params)."

    lines += [
        "",
        f"_Tested {n_combos} parameter combinations. "
        f"Sharpe improvement: {improvement:.1%} "
        f"({result.get('baseline_sharpe', 0):.4f} → {result.get('best_sharpe', 0):.4f})"
        f"{alpha_str}.{baseline_note}_",
        "",
        "| Parameter | Default | Current (S3) | Recommended | Drift from default |",
        "|-----------|---------|--------------|-------------|-------------------|",
    ]
    all_keys = sorted(set(list(baseline.keys()) + list(recommended.keys()) + list(factory.keys())))
    for k in all_keys:
        d = factory.get(k)
        b = baseline.get(k)
        r = recommended.get(k)
        d_str = f"{d:.4f}" if isinstance(d, float) else str(d) if d is not None else "—"
        b_str = f"{b:.4f}" if isinstance(b, float) else str(b) if b is not None else "—"
        r_str = f"{r:.4f}" if isinstance(r, float) else str(r) if r is not None else "—"
        if d is not None and r is not None and isinstance(d, (int, float)) and isinstance(r, (int, float)):
            drift = r - d
            drift_str = f"{'+' if drift >= 0 else ''}{drift:.4f}"
        else:
            drift_str = "—"
        lines.append(f"| {k} | {d_str} | {b_str} | {r_str} | {drift_str} |")

    lines += ["", f"> {result.get('note', '')}"]

    apply = result.get("apply_result", {})
    if apply.get("applied"):
        lines += [
            f"> ✅ **Executor params updated** in S3 (`config/executor_params.json`). "
            f"Executor Lambda will use new params on next cold-start.",
        ]
    else:
        reason = apply.get("reason", "guardrails not met")
        lines += [f"> ⏸ **Not applied** — {reason}."]

    return lines


def _pct(v) -> str:
    if v is None:
        return "—"
    return f"{v * 100:.1f}%"


def _fmt(v) -> str:
    if v is None:
        return "—"
    return f"{v:.3f}"
