"""
reporter.py — build markdown report + CSV output files, upload to S3.

Consumes output from signal_quality, regime_analysis, score_analysis, attribution,
and (when available) vectorbt portfolio stats. Writes:
    - results/{date}/report.md
    - results/{date}/signal_quality.csv
    - results/{date}/metrics.json
    - s3://alpha-engine-research/backtest/{date}/report.md  (if upload=True)
"""

import json
import logging
import os
from datetime import date
from pathlib import Path

import boto3
import pandas as pd
from botocore.exceptions import ClientError

logger = logging.getLogger(__name__)


def build_report(
    run_date: str,
    signal_quality: dict,
    regime_analysis: list[dict],
    score_analysis: list[dict],
    attribution: dict,
    portfolio_stats: dict | None = None,
    config: dict | None = None,
) -> str:
    """
    Build a markdown report string from analysis results.

    Returns the markdown string (also written to disk by save()).
    """
    lines = [
        f"# Alpha Engine Backtest Report",
        f"_Run date: {run_date}_",
        "",
        "---",
        "",
    ]

    # Signal quality summary
    lines += _section_signal_quality(signal_quality)
    lines += [""]

    # Score threshold analysis
    lines += _section_score_analysis(score_analysis)
    lines += [""]

    # Regime breakdown
    lines += _section_regime(regime_analysis)
    lines += [""]

    # Attribution
    lines += _section_attribution(attribution)
    lines += [""]

    # Portfolio simulation (Mode 2)
    if portfolio_stats:
        lines += _section_portfolio(portfolio_stats)
        lines += [""]

    lines += [
        "---",
        f"_Generated by alpha-engine-backtester — {run_date}_",
    ]

    return "\n".join(lines)


def save(
    report_md: str,
    signal_quality: dict,
    score_analysis: list[dict],
    run_date: str | None = None,
    results_dir: str = "results",
) -> Path:
    """
    Write report.md, signal_quality.csv, and metrics.json to results/{date}/.

    Returns the output directory path.
    """
    if run_date is None:
        run_date = date.today().isoformat()

    out_dir = Path(results_dir) / run_date
    out_dir.mkdir(parents=True, exist_ok=True)

    # Markdown report
    (out_dir / "report.md").write_text(report_md)
    logger.info("Wrote %s", out_dir / "report.md")

    # Signal quality CSV
    if score_analysis:
        df = pd.DataFrame(score_analysis)
        df.to_csv(out_dir / "signal_quality.csv", index=False)
        logger.info("Wrote %s", out_dir / "signal_quality.csv")

    # Metrics JSON (overall summary)
    overall = signal_quality.get("overall", {})
    metrics = {
        "run_date": run_date,
        "status": signal_quality.get("status"),
        **overall,
    }
    (out_dir / "metrics.json").write_text(json.dumps(metrics, indent=2, default=str))
    logger.info("Wrote %s", out_dir / "metrics.json")

    return out_dir


def upload_to_s3(
    local_dir: Path,
    bucket: str,
    prefix: str = "backtest",
    run_date: str | None = None,
) -> None:
    """
    Upload all files in local_dir to s3://{bucket}/{prefix}/{run_date}/.
    """
    if run_date is None:
        run_date = date.today().isoformat()

    s3 = boto3.client("s3")
    for file_path in local_dir.iterdir():
        key = f"{prefix}/{run_date}/{file_path.name}"
        try:
            s3.upload_file(str(file_path), bucket, key)
            logger.info("Uploaded s3://%s/%s", bucket, key)
        except ClientError as e:
            logger.error("Failed to upload %s: %s", file_path, e)
            raise


# --- Section builders ---

def _section_signal_quality(sq: dict) -> list[str]:
    lines = ["## Mode 1 — Signal Quality"]
    status = sq.get("status", "unknown")

    if status == "insufficient_data":
        lines += [
            "",
            f"> **Insufficient data.** "
            f"{sq.get('rows_10d_populated', 0)} rows with 10d returns populated "
            f"(need {sq.get('rows_needed', 10)}). "
            "Results will be available after Week 4 (~200 populated rows).",
        ]
        return lines

    overall = sq.get("overall", {})
    acc_10d = overall.get("accuracy_10d")
    acc_30d = overall.get("accuracy_30d")
    n_10d = overall.get("n_10d", 0)
    n_30d = overall.get("n_30d", 0)

    lines += [
        "",
        f"| Metric | 10d | 30d |",
        f"|--------|-----|-----|",
        f"| Accuracy vs SPY | {_pct(acc_10d)} (n={n_10d}) | {_pct(acc_30d)} (n={n_30d}) |",
        f"| Avg alpha | {_pct(overall.get('avg_alpha_10d'))} | {_pct(overall.get('avg_alpha_30d'))} |",
        "",
        "> 50% = coin flip. 55%+ over 30+ signals suggests real alpha.",
    ]

    buckets = sq.get("by_score_bucket", [])
    if buckets:
        lines += ["", "### By score bucket", ""]
        lines += ["| Bucket | Acc 10d | Acc 30d | Avg α 10d | n |"]
        lines += ["|--------|---------|---------|-----------|---|"]
        for b in buckets:
            lines.append(
                f"| {b.get('bucket')} | {_pct(b.get('accuracy_10d'))} | "
                f"{_pct(b.get('accuracy_30d'))} | {_pct(b.get('avg_alpha_10d'))} | "
                f"{b.get('n_10d', 0)} |"
            )

    return lines


def _section_score_analysis(rows: list[dict]) -> list[str]:
    lines = ["## Score threshold analysis"]
    if not rows:
        lines += ["", "> Deferred until Week 4+ (insufficient data)."]
        return lines

    lines += ["", "| Min score | Acc 10d | Acc 30d | n |"]
    lines += ["|-----------|---------|---------|---|"]
    for r in rows:
        lines.append(
            f"| {r.get('threshold')} | {_pct(r.get('accuracy_10d'))} | "
            f"{_pct(r.get('accuracy_30d'))} | {r.get('n_10d', 0)} |"
        )
    return lines


def _section_regime(rows: list[dict]) -> list[str]:
    lines = ["## Regime analysis"]
    if not rows:
        lines += ["", "> Deferred until Week 4+ (insufficient data)."]
        return lines

    lines += ["", "| Regime | Acc 10d | Acc 30d | n |"]
    lines += ["|--------|---------|---------|---|"]
    for r in rows:
        lines.append(
            f"| {r.get('market_regime')} | {_pct(r.get('accuracy_10d'))} | "
            f"{_pct(r.get('accuracy_30d'))} | {r.get('n_10d', 0)} |"
        )
    return lines


def _section_attribution(attr: dict) -> list[str]:
    lines = ["## Sub-score attribution"]
    status = attr.get("status", "unknown")

    if status != "ok":
        lines += [
            "",
            f"> **Deferred.** {attr.get('note', 'Insufficient data.')}",
        ]
        return lines

    lines += [
        "",
        f"Analyzed {attr.get('rows_analyzed', 0)} signals.",
        "",
        "### Correlation with beat_spy_10d",
        "",
        "| Sub-score | Corr (10d) | Corr (30d) |",
        "|-----------|------------|------------|",
    ]
    for label, corrs in attr.get("correlations", {}).items():
        c10 = corrs.get("beat_spy_10d")
        c30 = corrs.get("beat_spy_30d")
        lines.append(f"| {label} | {_fmt(c10)} | {_fmt(c30)} |")

    ranking_10d = attr.get("ranking_10d", [])
    if ranking_10d:
        lines += ["", f"**Strongest predictor (10d):** {ranking_10d[0]}"]

    lines += ["", f"> {attr.get('note', '')}"]
    return lines


def _section_portfolio(stats: dict) -> list[str]:
    return [
        "## Mode 2 — Portfolio simulation",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Total return | {_pct(stats.get('total_return'))} |",
        f"| Sharpe ratio | {_fmt(stats.get('sharpe_ratio'))} |",
        f"| Max drawdown | {_pct(stats.get('max_drawdown'))} |",
        f"| Calmar ratio | {_fmt(stats.get('calmar_ratio'))} |",
        f"| Total trades | {stats.get('total_trades', 'N/A')} |",
        f"| Win rate | {_pct(stats.get('win_rate'))} |",
    ]


def _pct(v) -> str:
    if v is None:
        return "—"
    return f"{v * 100:.1f}%"


def _fmt(v) -> str:
    if v is None:
        return "—"
    return f"{v:.3f}"
